language: python

python:
  - "2.7"

services:
  - postgresql

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database communitymaps;' -U postgres
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "create extension hstore"
  - cp core/settings/project.sample.py core/settings/project.py
  - python manage.py syncdb --all
  - python manage.py migrate --fake

install:
  - pip install -r requirements.txt

script: python manage.py test
